### ISSUE TITLE
How to I run the App

### ISSUE THREAD

**Issue by pasith3e** [mrlukasbos/Catan#25]
Hello,

this is a real stupid question for anyone how knows Java/Marven, but how do I run this App, after I build it?

Best Regards,
Pasithee

**Comment by RubenSmit** [comment]
Hello! Sorry we did not spot your question before. This is a hobby project for us so documentation is not very up-to-date. In short, we have a server that handles the game state. You can start this by running the main function in the main class. Using the webinterface found in https://github.com/mrlukasbos/catan-web you can play games against each other. It is also possible to create your own AI to compete. A example can be found here: https://github.com/mrlukasbos/catan-client.

This is project is work in progress, to there are still bugs and unfinished features.
